### ISSUE TITLE
Create Docker Hub repo

### ISSUE THREAD

**Issue by charlocharlie** [Ricardo-Osorio/epicgames-weekly-freegames#11]
Docker Hub is the standard for hosting public images. I created my [own page](https://hub.docker.com/r/charlocharlie/epicgames-weekly-freegames) to make my workflow simpler, however it's based off my fork, so I have to manually sync it to update the image.

@Ricardo-Osorio, when you get the time, are you able to set up a Docker Hub repo for this page? It's pretty simple to link a Github repo and set it up. Here's an example build configuration that I'm using: ![Example config](https://i.imgur.com/1PWXdmU.png)

**Comment by Ricardo-Osorio** [comment]
Will do 👍

**Comment by Ricardo-Osorio** [comment]
I just created it following your specs. You can find the repo [here](hub.docker.com/repository/docker/ricosorio/epicgames-weekly-freegames).

**Comment by CorySanin** [comment]
I believe [this](https://hub.docker.com/r/ricosorio/epicgames-weekly-freegames) is the link you want to use 😉

**Comment by Ricardo-Osorio** [comment]
I definitely didn't copy the right link! That's the right one indeed, thank you 🙂
