### ISSUE TITLE
environment vars not set

### ISSUE THREAD

**Issue by Gamewalker** [Ricardo-Osorio/epicgames-weekly-freegames#18]
Hi,

I tried everythinf from bulding it local to using the docker.io repo, I always get:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/main.py", line 239, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/main.py", line 218, in main
    if EMAIL:
UnboundLocalError: local variable 'EMAIL' referenced before assignment
```

any ideas? (I set the EMAIL and PASSWORD vars ...)

**Comment by CorySanin** [comment]
Can you share the command you used to bring up the docker image?

**Comment by Gamewalker** [comment]
I digged into it, the vars are set in def read_env_variables(): but not in def main():

if I do 
`global TIMEOUT, LOGIN_TIMEOUT, EMAIL, PASSWORD, LOGLEVEL, SLEEPTIME, TOTP, DEBUG` 
in main, the vars are set ... . Im not familiar with python ..

my run command is:
`sudo docker run -e EMAIL="XXX" -e PASSWORD="XXX" -e LOGLEVEL=DEBUG epicgames`

**Comment by Ricardo-Osorio** [comment]
I can confirm that is happening. I will work on it.

**Comment by Ricardo-Osorio** [comment]
This issue should have been spotted ealier by me before merging it into master.
For now I reverted the commit that introduces it and take a look at afterwards.
