### ISSUE TITLE
Timeout error if purchase_button = GET

### ISSUE THREAD

**Issue by Andrej730** [Ricardo-Osorio/epicgames-weekly-freegames#20]
I'm getting Timeout error at the following lines:
https://github.com/Ricardo-Osorio/epicgames-weekly-freegames/blob/3fb08e7b7a5f59ab0e314fa70cc00286ba0686dd/main.py#L193

https://github.com/Ricardo-Osorio/epicgames-weekly-freegames/blob/3fb08e7b7a5f59ab0e314fa70cc00286ba0686dd/main.py#L39

What helped me is to add 
```python
purchase_button.click()
```
before https://github.com/Ricardo-Osorio/epicgames-weekly-freegames/blob/3fb08e7b7a5f59ab0e314fa70cc00286ba0686dd/main.py#L193

**Comment by Ricardo-Osorio** [comment]
That click was indeed missing! Thank you very much
