### ISSUE TITLE
Script Failing

### ISSUE THREAD

**Issue by TheTrueCoder** [Ricardo-Osorio/epicgames-weekly-freegames#22]
I pulled your image from docker hub and ran it using:
sudo docker run -e EMAIL=(My Email) -e PASSWORD=(My Password) ricosorio/epicgames-weekly-freegames

But it failed with the message:
CRITICAL:egs-weekly-freegames:Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/main.py", line 216, in execute
    purchase_steps(browser)
  File "/usr/local/lib/python3.7/site-packages/main.py", line 37, in purchase_steps
    EC.visibility_of_element_located((By.XPATH, "//button[contains(@class,'btn-primary')]"))
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

I am running Pop!_OS 19.10 with Docker version 19.03.6, build 369ce74a3c

**Comment by Ricardo-Osorio** [comment]
Can you try running it with an increased timeout?
`docker run -e TIMEOUT=20 -e LOGIN_TIMEOUT=25 -e EMAIL=<EMAIL> -e PASSWORD=<PASSWORD> ricosorio/epicgames-weekly-freegames`

**Comment by Ricardo-Osorio** [comment]
Can you try pulling the newest image and run it again? Hopefully this was fixed by increasing the default timeout from 5s to 20s.

**Comment by TheTrueCoder** [comment]
Thank you! The update fixed my problem.
