### ISSUE TITLE
Dealing with Captcha

### ISSUE THREAD

**Issue by mattjmorgan** [Ricardo-Osorio/epicgames-weekly-freegames#23]
Any thoughts on how to deal with Captchas? Every time the script runs, it hits a captcha and there is a "Critical" failure. How should I get around this?

**Comment by CorySanin** [comment]
I'm going to just quietly drop this here... https://github.com/charlocharlie/epicgames-freegames-node

**Comment by mattjmorgan** [comment]
great

**Comment by Ricardo-Osorio** [comment]
> I'm going to just quietly drop this here... https://github.com/charlocharlie/epicgames-freegames-node

I am very happy to know this small project inspired you to build a more reliable version of the concept! And thank you for mentioning mine ! ❤️ 
I will drop a link to yours on my README :)
