### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by DenisSlobodyanyuk** [Ricardo-Osorio/epicgames-weekly-freegames#26]
Hi. I can't seem to figure out how to use this container. Is there an instructional document or video on how to use this? Is it supposed to be fully automatic once you enter your credentials in the json file? If so, 
1. what is webPortalConfig for, is it the management dashboard? It doesn't seem to load for me, only a refresh button in the top left corner.
2. how do I figure out the "totp"?
3. are notifiers required, what for?

**Comment by Ricardo-Osorio** [comment]
Hi @DenisSlobodyanyuk 

You can read about how to run this project in its README file although I would recommend you check out this [other project](https://github.com/charlocharlie/epicgames-freegames-node) as it's based on the epic API and has been updated more often than this one.

On top of that, and as a result of this project being focused on web scraping, the steps I wrote back then will most likely be outdated now.

**Comment by DenisSlobodyanyuk** [comment]
Thanks for your reply. I was actually looking at the project you sent me link for and accidentally opened an issue here instead of there.

**Comment by Ricardo-Osorio** [comment]
No worries 😄 👋
