### ISSUE TITLE
Game titles DOM element was updated

### ISSUE THREAD

**Issue by Ricardo-Osorio** [Ricardo-Osorio/epicgames-weekly-freegames#8]
Due to EpicGames latest update to the DOM elements that contain the game titles, the XPath used in the script is no longer able to retrieve them and prints empty strings instead.

The XPath should be updated to match the update.

Note: This doesn't prevent the script from running.

**Comment by CorySanin** [comment]
Charlie and I saw the game title appearing in our logs. I wonder if this is another regional difference or something.
